name: portfolio
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1
  url_launcher: 6.3.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/vectors/
    - assets/vectors/lang/
    - assets/images/


  uses-material-design: true


